USE [master]
GO

/****** Object:  Database [NorthWindDB]    Script Date: 27. 2. 2022 17:31:23 ******/
CREATE DATABASE [NorthWindDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NorthWindDB', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\NorthWindDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'NorthWindDB_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\NorthWindDB_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NorthWindDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NorthWindDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NorthWindDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NorthWindDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NorthWindDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NorthWindDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [NorthWindDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [NorthWindDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NorthWindDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NorthWindDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NorthWindDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NorthWindDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NorthWindDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NorthWindDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NorthWindDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NorthWindDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [NorthWindDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NorthWindDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NorthWindDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NorthWindDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NorthWindDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NorthWindDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NorthWindDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NorthWindDB] SET RECOVERY FULL 
GO

ALTER DATABASE [NorthWindDB] SET  MULTI_USER 
GO

ALTER DATABASE [NorthWindDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NorthWindDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NorthWindDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NorthWindDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [NorthWindDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [NorthWindDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [NorthWindDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [NorthWindDB] SET  READ_WRITE 
GO



USE [NorthWindDB]
GO

/****** Object:  Schema [stage]    Script Date: 27. 2. 2022 17:30:32 ******/
CREATE SCHEMA [stage]
GO

/****** Object:  Schema [stage]    Script Date: 27. 2. 2022 17:30:32 ******/
CREATE SCHEMA [edw]
GO


